#:kivy 1.11.1

#:import MenuBar MenuBar

<MenuBar>:
    
    orientation: 'horizontal'
    padding: 2

    Button:
        text: 'Return To Main Menu'
        on_release: root.ReturnToMainMenu(*args)
    Button:
        text: 'Go Back a Level' 
        on_release: app.GoPreviousScreen()
    Button:
        text: 'Options'
        disabled: True
    Button:
        text: 'Exit Application'
        on_release: app.stop()